lo-LA:
  rules:
    - maxWords: 500
      translators: [LO_T1@eqho.com]
    - maxWords: 2000
      translators: [LO_T3@eqho.com]
    - maxWords: null
      translators: [LO_T3@eqho.com, LO_T4@eqho.com]

km-KH:
  rules:
    - maxWords: 500
      translators: [kh_t1@eqho.com]
    - maxWords: 2000
      translators: [kh_t2@eqho.com]
    - maxWords: null
      translators: [kh_t3@eqho.com, kh_e2@eqho.com, kh_e3@eqho.com]
